In [100]:
import pandas as pd
import numpy as np

sdl = pd.read_excel('售电量分组.xlsx')
sdl = sdl.fillna(0)
sdl

                        组织名称      本年累计数       万千瓦时
0               四川富源电力股份有限公司  261209.18  26.120918
1         国网冀北电力有限公司三河市供电分公司  270190.26  27.019026
2         国网冀北电力有限公司丰宁县供电分公司   85553.93   8.555393
3         国网冀北电力有限公司乐亭县供电分公司  119928.78  11.992878
4         国网冀北电力有限公司兴隆县供电分公司   60802.09   6.080209
...                      ...        ...        ...
1376    国网黑龙江省电力有限公司鸡东县供电分公司   24726.52   2.472652
1377  国网黑龙江省电力有限公司鸡西市郊区供电分公司   30257.22   3.025722
1378  国网黑龙江省电力有限公司鹤岗市郊区供电分公司   22898.13   2.289813
1379    国网黑龙江省电力有限公司龙江县供电分公司   49656.75   4.965675
1380                 邹平县供电公司  311945.78  31.194578

[1381 rows x 3 columns]

In [101]:
sdl.describe()

              本年累计数         万千瓦时
count  1.381000e+03  1381.000000
mean   1.579258e+05    15.792576
std    2.063528e+05    20.635276
min   -9.838687e+04    -9.838687
25%    5.272521e+04     5.272521
50%    1.040173e+05    10.401733
75%    1.824760e+05    18.247605
max    2.363284e+06   236.328414

In [102]:
sdl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1381 entries, 0 to 1380
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   组织名称    1381 non-null   object
 1   本年累计数   1381 non-null   float64
 2   万千瓦时    1381 non-null   float64
dtypes: float64(2), object(1)
memory usage: 32.5+ KB

In [103]:
# 获取最大值和最小值并计算分组
sdl_max = np.max(sdl['万千瓦时'])
sdl_min = np.min(sdl['万千瓦时'])
bins_step = (sdl_max - sdl_min) / 30
bins = [i for i in np.arange(sdl_min, sdl_max, bins_step)]
bins.append(sdl_max)
# bins = np.round(bins)
bins

[-9.838687,
 -1.633116966666666,
 6.572453066666668,
 14.778023100000002,
 22.983593133333336,
 31.189163166666667,
 39.394733200000005,
 47.60030323333334,
 55.80587326666667,
 64.0114433,
 72.21701333333334,
 80.42258336666669,
 88.6281534,
 96.83372343333335,
 105.03929346666669,
 113.24486350000001,
 121.45043353333335,
 129.6560035666667,
 137.8615736,
 146.06714363333336,
 154.27271366666668,
 162.47828370000002,
 170.68385373333336,
 178.88942376666668,
 187.09499380000003,
 195.30056383333337,
 203.5061338666667,
 211.71170390000003,
 219.91727393333338,
 228.1228439666667,
 236.328414]

In [104]:
# 分组计数
bin_idx = []
for i in sdl['万千瓦时']:
    if i == bins[0]:
        bin_idx.append(0)
        continue
    for j in range(1, len(bins)):
        if i > bins[j - 1] and i <= bins[j]:
            bin_idx.append(j - 1)

bins_count = np.bincount(bin_idx)
bins_count

array([  2, 436, 485, 203, 108,  55,  29,  11,  15,   8,   4,   4,   4,
         3,   3,   1,   2,   1,   0,   2,   1,   0,   0,   0,   0,   0,
         0,   2,   0,   2], dtype=int64)

In [105]:
bins_count_avg = np.average(bins_count) / 2
bins_count_avg

23.016666666666666

In [106]:
# 重新分组
new_bins = [bins[0]]
new_bins_count = []
acc = 0
for i in range(len(bins_count)):
    acc += bins_count[i]
    if acc > bins_count_avg:
        new_bins.append(bins[i + 1])
        new_bins_count.append(acc)
        acc = 0
if acc != 0:
    new_bins.append(bins[len(bins) - 1])
    new_bins_count.append(acc)
np.round(new_bins)

array([-10.,   7.,  15.,  23.,  31.,  39.,  48.,  64., 113., 236.])

In [107]:
new_bins_count

[438, 485, 203, 108, 55, 29, 26, 26, 11]

In [108]:
# 打标签
new_bin_idx = []
for i in sdl['万千瓦时']:
    if i == new_bins[0]:
        new_bin_idx.append(0)
        continue
    for j in range(1, len(new_bins)):
        if i > new_bins[j - 1] and i <= new_bins[j]:
            new_bin_idx.append(j - 1)

In [109]:
new_bin_idx

[3,
 3,
 1,
 1,
 0,
 1,
 3,
 3,
 2,
 0,
 1,
 1,
 2,
 3,
 0,
 1,
 0,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 3,
 1,
 1,
 0,
 0,
 2,
 1,
 2,
 3,
 1,
 0,
 0,
 2,
 1,
 3,
 0,
 1,
 5,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 2,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 3,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 8,
 2,
 1,
 0,
 1,
 3,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 3,
 0,
 3,
 1,
 0,
 4,
 1,
 1,
 5,
 4,
 1,
 0,
 0,
 1,
 0,
 3,
 5,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 7,
 0,
 2,
 5,
 3,
 4,
 3,
 8,
 6,
 0,
 0,
 0,
 1,
 2,
 3,
 0,
 1,
 3,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 3,
 1,
 2,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 0,
 1,
 0,
 2,
 1,
 3,
 3,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 3,
 2,
 0,
 2,
 3,
 3,
 4,
 2,
 1,
 2,
 2,
 1,
 4,
 2,
 1,
 4,
 2,
 1,
 1,
 1,
 1,
 0,
 3,
 4,
 3,
 5,
 2,
 2,
 0,
 2,
 1,
 1,
 3,
 1,
 3,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 4,
 1,
 2,
 0,
 1,
 0,
 0,
 3,
 6,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 4,
 2,
 3,
 1,
 3,
 1,
 2,
 0,
 0,
 3,
 3,
 2,
 2,
 1,
 1,
 3,
 2,
 4,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 5,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 7,
 2,
 2,
 5,
 2,
 1,
 6,
 1,
 2,
 1,
 2,
 1,
 2,
 3,
 2,
 3,
 5,
 2,
 3,
 1,
 2,
 2,
 1,
 1,
 3,
 3,
 2,
 1,
 4,
 1,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 3,
 5,
 3,
 2,
 3,
 2,
 4,
 3,
 2,
 1,
 1,
 4,
 3,
 3,
 4,
 2,
 1,
 2,
 1,
 2,
 6,
 7,
 4,
 1,
 5,
 1,
 2,
 3,
 4,
 1,
 1,
 1,
 0,
 0,
 2,
 3,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 4,
 1,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 2,
 2,
 1,
 1,
 3,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 2,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 1,
 4,
 0,
 0,
 1,
 0,
 5,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 0,
 3,
 0,
 0,
 4,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 3,
 2,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 3,
 5,
 1,
 0,
 1,
 0,
 1,
 0,
 2,
 1,
 8,
 5,
 3,
 3,
 7,
 5,
 7,
 0,
 0,
 3,
 1,
 6,
 6,
 3,
 5,
 5,
 7,
 6,
 6,
 7,
 3,
 3,
 6,
 8,
 3,
 8,
 2,
 5,
 1,
 5,
 4,
 8,
 8,
 5,
 6,
 3,
 4,
 7,
 4,
 6,
 2,
 2,
 6,
 3,
 2,
 3,
 7,
 2,
 3,
 8,
 6,
 4,
 4,
 2,
 3,
 4,
 5,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 4,
 2,
 2,
 0,
 1,
 1,
 1,
 2,
 0,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 3,
 2,
 2,
 1,
 2,
 4,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 3,
 0,
 2,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 4,
 1,
 0,
 0,
 1,
 2,
 0,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 4,
 1,
 2,
 1,
 1,
 3,
 1,
 1,
 1,
 4,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 3,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 5,
 1,
 0,
 2,
 2,
 6,
 2,
 2,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 4,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 1,
 1,
 2,
 1,
 1,
 3,
 1,
 0,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 4,
 1,
 2,
 2,
 1,
 1,
 2,
 0,
 1,
 3,
 1,
 4,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 4,
 1,
 2,
 1,
 3,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 3,
 1,
 1,
 1,
 2,
 4,
 1,
 1,
 1,
 0,
 0,
 7,
 7,
 7,
 7,
 8,
 2,
 6,
 6,
 2,
 7,
 1,
 1,
 5,
 4,
 3,
 4,
 6,
 2,
 4,
 4,
 4,
 1,
 3,
 0,
 2,
 3,
 4,
 0,
 3,
 1,
 6,
 0,
 2,
 0,
 4,
 6,
 6,
 5,
 7,
 1,
 7,
 2,
 3,
 3,
 6,
 ...]